server {
    listen 80;
    server_name _;
    client_max_body_size 10M;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://karma-api-library:3000/api/;
        proxy_set_header Host $host;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    location /uploads/ {
        proxy_pass http://karma-api-library:3000/uploads/;
        proxy_set_header Host $host;
    }
}
